FROM node:14.18.3
RUN npm install pm2 -g
WORKDIR /app
COPY package*.json ./
RUN npm install
RUN npm ci --only=production
COPY . /app
WORKDIR /app/msTeamsBot
RUN npm install
WORKDIR /app
EXPOSE 5000 5001 3978
CMD [ "pm2-runtime", "start", "ecosystem.config.js" ]
