services:
  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - NETWORK_NAME
    labels:
      traefik.enable: 'true'
      traefik.port: 80
      traefik.http.routers.nginx.rule: Host(`DNS_NAME`)
      traefik.http.routers.nginx.entrypoints: websecure
      traefik.http.routers.nginx.tls: true
      traefik.http.routers.nginx.tls.certresolver: myresolver

  traefik:
    image: traefik:v2.3
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - 80:80
      - 443:443
    networks:
      - NETWORK_NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json


networks:
  NETWORK_NAME:
    external: true
