version: "3.5"
services:
  app:
    container_name: CONTAINER_NAME
    build:
      context: .
      dockerfile: PATH_TO_DOCKERFILE
    env_file: .env
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  :node_modules
